function frametachorpm = F_Time_Feature_TachoRPM(signal, fs )

h = tachorpm(signal,fs);
frametachorpm=[max(h),...
               min(h),...
               mode(h),...
               mean(h),...
               std(h),...
               (max(h)-min(h))];

end
