function features = F_Time_Feature_GradientAnalysis(frame, peakNumber)

up = gradient(frame);

[pks,locs,widths,proms] = findpeaks(up,'SortStr','descend','NPeaks',peakNumber);

features=[mean(pks), mean(diff(locs)), mean(widths), mean(proms),...
    F_Time_Feature_RMS(up),...
    F_Time_Feature_Variance(up),...
    F_Time_Feature_Peak2Peak(up),...
    F_Time_Feature_Max(up),...
    F_Time_Feature_Mean(up),...
    F_Time_Feature_Min(up),...
    F_Time_Feature_Peak2RMS(up),...
    F_Time_Feature_Std(up),...
    F_Time_Feature_Skewness(up),...
    F_Time_Feature_Median(up),...
    F_Time_Feature_Kurtosis(up)
    ];

%TODO: Add more gradient analysis

end