function frameSlewRate = F_Time_Feature_SlewRate(signal, fs )

h = slewrate(signal,fs);

try
    [pks,locs,widths,proms] = findpeaks(h,'SortStr','descend','NPeaks',3);
    
    frameSlewRate=[max(h),...
        min(h),...
        mode(h),...
        mean(h),...
        std(h),...
        (max(h)-min(h)),...
        mean(pks),...
        mean(diff(locs)),...
        mean(widths),...
        mean(proms)
        ];
catch
    try
        [pks,locs,widths,proms] = findpeaks(h,'SortStr','descend','NPeaks',2);
        
        frameSlewRate=[max(h),...
            min(h),...
            mode(h),...
            mean(h),...
            std(h),...
            (max(h)-min(h)),...
            mean(pks),...
            mean(diff(locs)),...
            mean(widths),...
            mean(proms)
            ];
    catch
        frameSlewRate=zeros(1,10);
    end
    
    
end

end
